# Generated by Django 3.2.19 on 2023-06-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.FloatField()),
                ('total_peice', models.FloatField()),
                ('stock_status', models.CharField(max_length=15)),
            ],
        ),
    ]
